<?php

namespace Folklore\Mediatheque\Jobs;

use Exception;
use Folklore\Mediatheque\Contracts\Models\PipelineJob as PipelineJobModel;
use Folklore\Mediatheque\Contracts\Support\HasPipelines as HasPipelinesInterface;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Bus\Dispatcher;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Log;

class RunPipelineJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public $pipelineJob;

    public $pipeline;

    public $model;

    /**
     * The number of seconds the job can run, null to use the worker's timeout
     *
     * @var int|null
     */
    public $timeout;

    /**
     * The number of times the job may be attempted, null to use the worker's tries
     *
     * @var int|null
     */
    public $tries;

    /**
     * Fail the job when it times out instead of running it again
     *
     * @var bool
     */
    public $failOnTimeout = true;

    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct(PipelineJobModel $job, HasPipelinesInterface $model)
    {
        $this->pipelineJob = $job;
        $this->pipeline = $job->pipeline;
        $this->model = $model;

        $definition = $job->getDefinition();
        $this->timeout = $this->getQueueOption($definition, 'timeout');
        $this->tries = $this->getQueueOption($definition, 'tries');
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle(Log $log)
    {
        $pipelineJob = $this->pipelineJob;
        $definition = $pipelineJob->getDefinition();
        $name = $pipelineJob->getName();
        $pipelineDefintion = $this->pipeline->getDefinition();
        $jobClass = $definition['job'];
        $fromFile = data_get($definition, 'from_file', $pipelineDefintion->fromFile());

        // Check if the file exists
        $file = $this->model->getFile($fromFile);
        if (! $file) {
            throw new Exception('File "'.$fromFile.'" is not available.');
        }

        $pipelineJob->markStarted();

        // Run the job, then delete the local files it created
        $options = Arr::except($definition, ['from_file', 'job']);
        $job = new $jobClass($file, $options, $this->model);
        try {
            $newFile = app(Dispatcher::class)->dispatchSync($job);
        } finally {
            if (method_exists($job, 'deleteTemporaryFiles')) {
                $job->deleteTemporaryFiles();
            }
        }

        // Add files generated by the job to the model
        $isIndexed = is_array($newFile);
        $files = ! is_array($newFile) ? [$newFile] : $newFile;
        foreach ($files as $index => $file) {
            if (is_null($file)) {
                continue;
            }
            $fileHandle = null;
            if ($isIndexed) {
                $fileHandle = ! is_null($name) && is_numeric($index) ? $name.'.'.$index : $index;
            } else {
                $fileHandle = $name;
            }
            if (! is_null($fileHandle)) {
                $this->model->setFile($fileHandle, $file);
            } else {
                $this->model->addFile($file);
            }
        }

        $pipelineJob->markEnded();

        $this->model->load('files');
        $this->pipeline->load('jobs');
        $this->model->touch();

        // Run the jobs waiting for the file created by this job, or fail them
        // if the job did not create it
        foreach ($this->pipeline->getJobs() as $waitingJob) {
            if (! $waitingJob->isWaitingForFile($name)) {
                continue;
            }
            if ($this->model->hasFile($name)) {
                $waitingJob->run();
            } else {
                $this->failJob($waitingJob, 'Job "'.$name.'" did not create the file "'.$name.'".');
            }
        }

        $this->endPipelineIfAllJobsEnded();
    }

    /**
     * The job failed to process.
     *
     * @param  Exception  $exception
     * @return void
     */
    public function failed($exception = null)
    {
        $this->pipeline->load('jobs');
        $this->failJob($this->pipelineJob, $exception);
        $this->endPipelineIfAllJobsEnded();
    }

    /**
     * Mark a job as failed, with the jobs waiting for its file
     *
     * @param  \Throwable|string|null  $reason
     */
    protected function failJob(PipelineJobModel $job, $reason = null): void
    {
        $job->markFailed($reason);

        $name = $job->getName();
        foreach ($this->pipeline->getJobs() as $waitingJob) {
            if ($waitingJob->isWaitingForFile($name)) {
                $this->failJob($waitingJob, 'Job "'.$name.'" failed.');
            }
        }
    }

    /**
     * Mark the pipeline as ended, or failed, once none of its jobs is pending or running
     */
    protected function endPipelineIfAllJobsEnded(): void
    {
        if (! $this->pipeline->allJobsEnded()) {
            return;
        }

        if ($this->pipeline->hasFailedJobs()) {
            $this->pipeline->markFailed();
        } else {
            $this->pipeline->markEnded();
        }
    }

    /**
     * Get a queue option from the job definition, or from the config
     */
    protected function getQueueOption(array $definition, string $key): ?int
    {
        $value = data_get($definition, $key, config('mediatheque.jobs.'.$key));

        return is_null($value) || $value === '' ? null : (int) $value;
    }
}
